config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users,  only: [:show, :index] do
    resource :following, only: [:show, :create, :destroy], controller: "user/following"
    resource :follower, only: [:show], controller: "user/follower"
  end
  root "books#index"
  resources :books, shallow: true do
    resources :comments, only: [:create, :edit, :update, :destroy], module: "book"
  end
  resources :reports, shallow: true do
    resources :comments, only: [:create, :edit, :update, :destroy], module: "report"
  end
end

app/views/shared/_comment_form.html.erb
<%= form_with model: comment, local: true do |f| %>
  <div class= form-group>
    <%= f.label :content%>
    <%= f.text_area :content, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/shared/_comments.html.erb
<% comments.each do |comment| %>
  <div class="card mb-2 p-1" style="width: 25rem;">
    <%= br_with_escape(comment.content) %>
    <%= link_to comment.user.name, comment.user %>
    <%= l(comment.created_at, format: :long) %>

    <% if comment.user == current_user %>
      <%= link_to t("comments.edit"), edit_comment_path(comment)%>
      <%= link_to t("comments.delete"), comment_path(comment), method: :delete, data: { confirm: t("comments.delete_confirmation") } %>
    <% end%>
  </div>
<%end%>