config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users,  only: [:show, :index] do
    resource :following, only: [:show, :create, :destroy], controller: "user/following"
    resource :follower, only: [:show], controller: "user/follower"
  end
  root "books#index"
  resources :books, shallow: true do
    resources :comments, only: [:create, :edit, :update, :destroy], module: "book"
  end
  resources :reports, shallow: true do
    resources :comments, only: [:create, :edit, :update, :destroy], module: "report"
  end
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  include Commentable

  belongs_to :user

  mount_uploader :picture, PictureUploader
  scope :recent_following_books, ->(followings) { includes(:user).where(users: { id: followings }).order(created_at: :desc) }
  scope :recent_follower_books, ->(follower) { includes(:user).where(users: { id: follower }).order(created_at: :desc) }
end

app/controllers/book/comments_controller.rb
# frozen_string_literal: true

class Book::CommentsController < ::CommentsController
  def create
    @commentable = find_book
    super
  end

  private
    def find_book
      Book.find(params[:book_id])
    end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :verify_posted_user, only: [:edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.page params[:page]
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @comments = @book.comments.includes(:user)
    @comment = @book.comments.build
  end

  # GET /books/new
  def new
    @book = current_user.books.build
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.build(book_params)
    if @book.save
      redirect_to @book, notice: t(".success")
    else
      render :new
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    if @book.update(book_params)
      redirect_to @book, notice: t(".update")
    else
      render :edit
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    redirect_to books_url, notice: t(".destroy")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    def verify_posted_user
      # 403ページ未作成
      head :forbidden unless @book.user == current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :memo, :author, :picture)
    end
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_area :memo %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to t(".show"), @book %> |
<%= link_to t("views.defaults.back"), books_path %>

app/views/books/index.html.erb
<h1>Books</h1>
<p>added some text</p>
<table>
  <thead>
    <tr>
      <th><%= Book.human_attribute_name(:title) %></th>
      <th><%= Book.human_attribute_name(:memo) %></th>
      <th><%= Book.human_attribute_name(:author) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.memo %></td>
        <td><%= book.author %></td>
        <td><%= link_to t(".show"), book %></td>
        <% if book.user == current_user %>
          <td><%= link_to t(".edit"), edit_book_path(book)  %></td>
          <td><%= link_to t(".destroy"), book, method: :delete, data: { confirm: t(".check_destroy")  } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @books %>
<%= link_to t(".new"), new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p>
  <strong><%= Book.human_attribute_name(:title) %></strong>
  <%= @book.title %>
</p>

<p>
  <strong><%= Book.human_attribute_name(:memo) %></strong>
  <%= @book.memo %>
</p>

<p>
  <strong><%= Book.human_attribute_name(:author) %></strong>
  <%= @book.author %>
</p>

<p>
  <strong><%= Book.human_attribute_name(:picture) %></strong>
  <%= image_tag(@book.picture_url) if @book.picture.present? %>
</p>

<p>
  posted by <%= link_to @book.user.name, user_path(@book.user) %>
</p>

<h2><%= t("comments.comment") %></h2>
<%= render "shared/comments", comments: @comments%>

<h2><%= t("comments.post_comment") %></h2>
<%= render "shared/comment_form", comment: [@book, @comment]%>

<%= link_to t(".edit"), edit_book_path(@book) %> |
<%= link_to t("views.defaults.back"), books_path %>