config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users,  only: [:show, :index] do
    resource :following, only: [:show, :create, :destroy], controller: "user/following"
    resource :follower, only: [:show], controller: "user/follower"
  end
  root "books#index"
  resources :books, shallow: true do
    resources :comments, only: [:create, :edit, :update, :destroy], module: "book"
  end
  resources :reports, shallow: true do
    resources :comments, only: [:create, :edit, :update, :destroy], module: "report"
  end
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  include Commentable

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true

  scope :recent_reports, -> { order(created_at: :desc) }
end

app/controllers/report/comments_controller.rb
# frozen_string_literal: true

class Report::CommentsController < ::CommentsController
  def create
    @commentable = find_report
    super
  end

  private
    def find_report
      Report.find(params[:report_id])
    end
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  def index
    @reports = Report.all.recent_reports
  end

  def show
    @report = find_report
    @comments = @report.comments.includes(:user)
    @comment = @report.comments.build
  end

  def new
    @report = current_user.reports.build
  end

  def create
    @report = current_user.reports.build(report_params)
    if @report.save
      redirect_to @report, notice: t(".success")
    else
      render :new
    end
  end

  def edit
    @report = find_report
  end

  def update
    @report = Report.find(params[:id])
    if @report.update(report_params)
      redirect_to @report, notice: t(".success")
    else
      render :edit
    end
  end

  def destroy
    @report = find_report
    @report.destroy
    redirect_to reports_url, notice: t(".success")
  end

  private
    def find_report
      Report.find(params[:id])
    end

    def report_params
      params.require(:report).permit(:title, :body)
    end
end

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control", rows: "8" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Edit Report</h1>
<%= render "form", report: @report%>

app/views/reports/index.html.erb
<h1>Reports</h1>
<%= link_to t(".new_report"), new_report_path, class:"btn btn-outline-secondary mb-4"%>

<% @reports.each do |report| %>
  <div class="card mb-2">
    <h3><%= link_to report.title, report %></h3>
    <div class="d-inlne-block">
      posted by: <%= link_to report.user.name, report.user %>,
      <%= l(report.created_at, format: :long) %>
    </div>

    <% if report.user == current_user %>
      <div>
        <div class="d-inline-block">
          <%= link_to t(".edit"), edit_report_path(report), class: "btn btn-outline-primary inline" %>
        </div>
        <div class="d-inline-block">
          <%= link_to t(".delete"), report, method: :delete, class: "btn btn-outline-danger", data: { confirm: t(".alert_delete") } %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/reports/new.html.erb
<h1>New Report</h1>
<%= render "form", report: @report%>

app/views/reports/show.html.erb
<div class="d-inline-block mt-2">
  posted by: <%= link_to @report.user.name, @report.user %>,
  <%= l(@report.created_at, format: :long) %>
</div>

<h1><%= @report.title %></h1>
<%= br_with_escape(@report.body) %>

<% if @report.user == current_user %>
  <div>
    <div class="d-inline-block mb-3">
      <%= link_to t(".edit"), edit_report_path(@report), class: "btn btn-outline-primary inline" %>
    </div>
    <div class="d-inline-block">
      <%= link_to t(".delete"), @report, method: :delete, class: "btn btn-outline-danger", data: { confirm: t(".alert_delete") } %>
    </div>
  </div>
<% end %>

<h2><%= t("comments.comment") %></h2>
<%= render "shared/comments", comments: @comments%>

<h2><%= t("comments.post_comment") %></h2>
<%=render "shared/comment_form", comment: [@report, @comment]%>

<%= link_to t(".report_list"), reports_path %>