config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users,  only: [:show, :index] do
    resource :following, only: [:show, :create, :destroy], controller: "user/following"
    resource :follower, only: [:show], controller: "user/follower"
  end
  root "books#index"
  resources :books, shallow: true do
    resources :comments, only: [:create, :edit, :update, :destroy], module: "book"
  end
  resources :reports, shallow: true do
    resources :comments, only: [:create, :edit, :update, :destroy], module: "report"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   <%= stylesheet_pack_tag 'application' %>
   <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <% key = "info" if key == "notice" %>
        <% key = "danger" if key == "alert" %>
        <%= content_tag :div, value, class: "alert alert-#{key}", role: "alert" %>
      <% end %>

      <% if user_signed_in? %>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <!-- 仮メニュー navbarにする -->
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to "home", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "reports", reports_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "mypage", user_path(current_user), class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "users", users_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "following", user_following_path(current_user), class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "follower", user_follower_path(current_user), class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "edit", edit_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "logout", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
        </ul>
      </nav>
      <% end %>
      <%= yield %>
      </div>
  </body>
</html>